version: "3.3"

services:
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: solder
      MYSQL_USER: solder
      MYSQL_PASSWORD: solder
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "4306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql

  setup:
    image: solder
    depends_on:
      - mysql
    volumes:
      - ./docker/setup.sh:/var/www/html/setup.sh
      - .:/var/www/html
    working_dir: /var/www/html
    command: [ "/bin/bash", "./setup.sh" ]
